//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Question_Id { get; set; }
        public int Answer_Id { get; set; }
        public int Quiz_Id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
    }
}
